checkFilename:
	gcc -std=c11 -Wall -o checkFilename checkFilename.c

checkformat:
	gcc -std=c11 -Wall -o checkformat checkformat.c

#contains:
#	gcc -std=c11 -Wall -o contains contains.c

.PHONY: clean
clean:
	rm -i checkFilename checkformat