strlength:
	gcc -std=c11 -Wall -o strlength strlength.c

lawn:
	gcc -std=c11 -Wall -o lawn lawn.c -lm

base2dec:
	gcc -std=c11 -Wall -o base2dec base2dec.c

randomSentence:
	gcc -std=c11 -Wall -o randomSentence randomSentence.c

.PHONY: clean
clean:
	rm -i strlength lawn base2dec randomSentence