ascii:
	gcc -std=c11 -Wall -o ascii ascii.c

gravity:
	gcc -std=c11 -Wall -o gravity gravity.c

gravity2:
	gcc -std=c11 -Wall -o gravity2 gravity2.c

.PHONY: clean
clean:
	rm -i ascii gravity gravity2 planetInfo.txt