sec2hms:
	gcc -std=c11 -Wall -o sec2hms sec2hms.c

stats:
	gcc -std=c11 -Wall -o stats stats.c

loadData:
	gcc -std=c11 -Wall -o loadData loadData.c

.PHONY: clean
clean:
	rm -i sec2hms stats loadData